import styled from 'styled-components';

export const ImageWithText = styled.div`
  position: relative;
  display: inline-block;
 

`;

export const Imagess = styled.img`
  width: 100vw; /* Dostosuj szerokość obrazka */
  height: 600px;
`;

export const Textss = styled.span`
  position: absolute;
  top: 50%;
  left: 50%;
  margin-left: auto;
  margin-right: auto;
  transform: translate(-50%, -50%); /* Wycentrowanie tekstu */
  font-size: 100px; /* Dostosuj rozmiar czcionki */
  color: whitesmoke; /* Kolor tekstu */
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); /* Dodanie cienia tekstu */
  opacity:0.6;
  letter-spacing: 3px;
  font-weight: 800;
  -webkit-animation: tilt-in-top-1 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: tilt-in-top-1 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-3-3 22:2:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tilt-in-top-1
 * ----------------------------------------
 */
@-webkit-keyframes tilt-in-top-1 {
  0% {
    -webkit-transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
            transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
    opacity: 0.5;
  }
  100% {
    -webkit-transform: rotateY(0deg) translateY(0) skewY(0deg);
            transform: rotateY(0deg) translateY(0) skewY(0deg);
    opacity: 0.5;
  }
}
@keyframes tilt-in-top-1 {
  0% {
    -webkit-transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
            transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
    opacity: 0.5;
  }
  100% {
    -webkit-transform: rotateY(0deg) translateY(0) skewY(0deg);
            transform: rotateY(0deg) translateY(0) skewY(0deg);
    opacity: 0.5;
  }
}
`;