import styled, {createGlobalStyle} from "styled-components";

export const Global= createGlobalStyle`
body
{
margin: 0;
background-color:#23ab0e ;
}`

export const Wrappercontent=styled.div`
margin-left:auto;
margin-right:auto;
width: 80vw;
margin-bottom: 50px;

height: auto;
margin-top: 50px;

@media screen and (max-width: 540px) {
display: flex;
flex-direction: column;
overflow-x: hidden;
}
`
export const Titlecontact=styled.text`
width:auto;
height:auto;
font-size:40px;
font-weight:700;
-webkit-animation: bounce-in-fwd 4s both;
	        animation: bounce-in-fwd 4s both;
    /* ----------------------------------------------
 * Generated by Animista on 2024-2-25 22:30:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-fwd
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-fwd {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: scale(0.7);
            transform: scale(0.7);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: scale(0.84);
            transform: scale(0.84);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  89% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: scale(0.95);
            transform: scale(0.95);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-fwd {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: scale(0.7);
            transform: scale(0.7);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: scale(0.84);
            transform: scale(0.84);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  89% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: scale(0.95);
            transform: scale(0.95);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}


@media screen and (min-width:280px){
    font-size:20;
    overflow-x: hidden;
}
@media screen and (max-width:1380px){
    font-size:40px;
    overflow-x: hidden;
}
`
export const Paragraphtitle=styled.div`
font-size: 20;

margin-top: 30px;
-webkit-animation: bounce-in-right 1.1s both;
	        animation: bounce-in-right 1.1s both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-2-25 22:38:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-right
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-right {
  0% {
    -webkit-transform: translateX(600px);
            transform: translateX(600px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateX(68px);
            transform: translateX(68px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateX(32px);
            transform: translateX(32px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-right {
  0% {
    -webkit-transform: translateX(600px);
            transform: translateX(600px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateX(68px);
            transform: translateX(68px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateX(32px);
            transform: translateX(32px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}

`
export const Maincontent=styled.div`
width: auto;
height: auto;
margin-top:20px;
display:flex;
justify-content:space-between;
@media screen and (max-width: 540px) {
display: flex;
flex-direction: column;
}
`
export const Informationcontent=styled.div`
width:300px;
height:auto;
display: flex;
flex-direction: column;

margin-top: 30px;
`
export const Textinformation=styled.text`
width: auto;
height:auto;
margin-top: 15px;
margin-bottom: 15px;

p{
    margin:0;
}
span{
    font-weight: 700;
    margin-right: 5px;
}
`
export const Wrapperinput=styled.div`
width: 300px;
height:400px;

margin-top: 30px;
display: flex;
flex-direction: column;

`
export const Inputdate=styled.input`
width: 200px;
height: 35px;

margin-bottom:10px;
margin-left: auto;
font-size:20px;

`
export const Inputmessage=styled.input`
width: 400px;
  height: 315px;
  margin-left: 10px;
  display: flex;
  
  justify-content: flex-start;
  align-items: flex-start; /* Rozpocznij pisanie od lewego górnego rogu */
   /* Umieść tekst w lewym górnym rogu */
  @media screen and (max-width: 540px) {
        width: 200px;
        height: 300px;
        overflow-x: hidden;
        margin-left: 10px;
        margin-bottom: 30px;
  }
  @media screen and (min-width: 768px)and  (max-width:1380px) {
        width:80px;
        height:320px;
        
  }
`
export const Titleinput=styled.label`
width: auto;
height: auto;
display: flex;
font-size: 15px;
margin-bottom: 20px;
padding-left: 0;




`
export const Messagecheckbox=styled.input`
width:15px;
height: 15px;
display: flex;
align-self: flex-start;
margin-left:0;



`
export const Sendquestion=styled.button`
width: 300px;
height: 50px;
background-color: darkblue;
margin-top: 30px;
color:white;
font-weight: 600;
text-transform: uppercase;
font-size: 20;
margin-left: 800px;
border: 1px solid darkblue;
display: flex;
justify-content: center;
align-items: center;


:hover{
    background-color: blue;
    cursor: pointer;
}
@media screen and (max-width: 540px) {
display: flex;
flex-direction: column;
margin-left: auto;
margin-right: auto;
justify-content: center;
align-items: center;
width: auto;

}
@media screen and (min-width: 768px)and  (max-width:1024px) {
        margin-left: auto;
        margin-right: auto;
}
`