import styled, {createGlobalStyle} from "styled-components";

export const Global= createGlobalStyle`
body
{
margin: 0;
background-color:#23ab0e ;
}`


export const Textrules=styled.div`
width: 1000px;

margin-left: auto;
margin-right: auto;
text-align: center;
border:3px solid rebeccapurple;
font-size: 20px;
margin-top: 50px;
font-weight: bold;
`
export const Wrappermodal=styled.div`
width: 1400px;
height:400px;
display: flex;
justify-content: space-between;
margin-left: auto;
margin-right: auto;
margin-top: 20px;

@media screen and (max-width: 1024px) {
  display: flex;
  flex-direction: column;
  height: auto;
  width: 100%;
  overflow-x: hidden;
  margin-left:auto;
  margin-right: auto;
  
}
`



export const Figurephoto=styled.figure`
@media screen and (max-width:1024px ){
  margin-left: auto;
  margin-right: auto;
}

`
export const Figcaptionphoto=styled.figcaption`
text-align: center;
font-size: 20px;
font-weight: 600;
margin-top: 10px;
color: ivory;
@media screen and (max-width:540px ){
  margin-left: auto;
  margin-right: auto;
}
`
export const Titlegalleries=styled.div`
margin-left: auto;
margin-right: auto;
width: 500px;
height:50px;
text-align: center;
font-size: 40px;

letter-spacing: 3px;
font-weight: 800;
margin-top: 30px;
background: linear-gradient(80deg,#bd1c4c,#bd1cbd);
-webkit-background-clip: text;
background-clip: text;
-webkit-text-fill-color: transparent;
-webkit-animation: scale-in-center 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: scale-in-center 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-2-24 17:29:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 1;
  }
}
@keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 1;
  }
}
@media screen and (max-width: 540px) {
  font-size:30px;
  margin-left: auto;
  margin-right:auto ;
  width: 100%;
}
`
export const Titlerules=styled.div`
width: 700px;
height: auto;
margin-left: auto;
margin-right: auto;
font-size: 50px;
font-weight: 600;
color:yellowgreen;

text-align: center;
margin-top: 30px;
-webkit-animation: rotate-in-bl 1s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: rotate-in-bl 1s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
          /* ----------------------------------------------
 * Generated by Animista on 2024-3-7 21:57:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-in-bl
 * ----------------------------------------
 */
@-webkit-keyframes rotate-in-bl {
  0% {
    -webkit-transform: rotate(-360deg);
            transform: rotate(-360deg);
    -webkit-transform-origin: bottom left;
            transform-origin: bottom left;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
    -webkit-transform-origin: bottom left;
            transform-origin: bottom left;
    opacity: 1;
  }
}
@keyframes rotate-in-bl {
  0% {
    -webkit-transform: rotate(-360deg);
            transform: rotate(-360deg);
    -webkit-transform-origin: bottom left;
            transform-origin: bottom left;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
    -webkit-transform-origin: bottom left;
            transform-origin: bottom left;
    opacity: 1;
  }
}
`
export const Rulesul=styled.ol`
width: auto;
height: auto;
font-size: 23px;
color:lightgoldenrodyellow;
margin-left: 100px;
li{
color:ghostwhite;
margin-left:10px;
font-size:18px;
}
`