import styled, {createGlobalStyle} from "styled-components";

export const Global= createGlobalStyle`
body
{
margin: 0;
background-color:#23ab0e ;
}`


export const Textrules=styled.div`
width: 1000px;

margin-left: auto;
margin-right: auto;
text-align: center;
border:3px solid rebeccapurple;
font-size: 20px;
margin-top: 50px;
font-weight: bold;
`
export const Wrappermodal=styled.div`
width: 1400px;
height:400px;
display: flex;
justify-content: space-between;
margin-left: auto;
margin-right: auto;
margin-top: 20px;
`



export const Figurephoto=styled.figure`


`
export const Figcaptionphoto=styled.figcaption`
text-align: center;
font-size: 20px;
font-weight: 600;
margin-top: 10px;
color: ivory;
`
export const Titlegalleries=styled.div`
margin-left: auto;
margin-right: auto;
width: 500px;
height:50px;
text-align: center;
font-size: 40px;
letter-spacing: 3px;
font-weight: 800;
margin-top: 30px;
background: linear-gradient(80deg,#bd1c4c,#bd1cbd);
-webkit-background-clip: text;
background-clip: text;
-webkit-text-fill-color: transparent;
-webkit-animation: scale-in-center 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: scale-in-center 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            /* ----------------------------------------------
 * Generated by Animista on 2024-2-24 17:29:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 1;
  }
}
@keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 1;
  }
}

`